export const TELEGRAM_API_KEY = process.env.NEXT_PUBLIC_TELEGRAM_API_KEY!;
export const TELEGRAM_API_URL = process.env.NEXT_PUBLIC_TELEGRAM_API_URL!;
export const TELEGRAM_CHAT_ID = process.env.NEXT_PUBLIC_TELEGRAM_CHAT_ID!;
